### ISSUE TITLE
__main__ doesn't work properly

### ISSUE THREAD

**Issue by QFSW** [QFSW/Pyanoboard#4]
Using the repository as a package
```bash
python -m pyanoboard example/config.json
```
yields the following
```bash
Traceback (most recent call last):
  File "C:\PROGRAM FILES\PYTHON 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\PROGRAM FILES\PYTHON 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yusuf\Development\Python\pyanoboard\pyanoboard\__main__.py", line 9, in <module>
    main()
  File "C:\Users\Yusuf\Development\Python\pyanoboard\pyanoboard\__main__.py", line 5, in main
    pyanoboard.main()
AttributeError: module 'pyanoboard' has no attribute 'main'
```

**Comment by QFSW** [comment]
This has been resolved in V1.1.0
